# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-12 12:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='addict_user',
            name='past_nickname',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
