# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-13 07:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_addict_user_past_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addict_user',
            name='credit',
            field=models.IntegerField(default=400),
        ),
        migrations.AlterField(
            model_name='addict_user',
            name='nickname',
            field=models.CharField(default='', max_length=100),
        ),
    ]
